// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDSe0nHlKapuZLVcQNfNxEUIx4kBrRHJIc',
    appId: '1:159109061162:web:3cee3119da504e820e0153',
    messagingSenderId: '159109061162',
    projectId: 'androiddevhomework',
    authDomain: 'androiddevhomework.firebaseapp.com',
    storageBucket: 'androiddevhomework.firebasestorage.app',
    measurementId: 'G-KZ20VE6GJJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAySIs5rmj2-pQh-h50IKg_pkD7zb7PNd4',
    appId: '1:159109061162:android:2901c4008fb25f870e0153',
    messagingSenderId: '159109061162',
    projectId: 'androiddevhomework',
    storageBucket: 'androiddevhomework.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDSe0nHlKapuZLVcQNfNxEUIx4kBrRHJIc',
    appId: '1:159109061162:web:8458bb178bc55d170e0153',
    messagingSenderId: '159109061162',
    projectId: 'androiddevhomework',
    authDomain: 'androiddevhomework.firebaseapp.com',
    storageBucket: 'androiddevhomework.firebasestorage.app',
    measurementId: 'G-F71ED920PZ',
  );
}
